# Task 1: Data Cleaning and Preprocessing

## Objective: Clean and prepare a raw dataset (with nulls, duplicates, inconsistent formats)
### Tools: Excel / Python (Pandas)
## Deliverables: Cleaned dataset + short summary of changes

## importing required libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Loading dataset

In [5]:
df=pd.read_csv("Sales-Export_2019-2020.csv")

In [6]:
df

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,4/2/2020,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160
...,...,...,...,...,...,...,...,...,...,...
995,France,"46,296.26",40319.41,5/15/2020,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
996,Belgium,"118,061.05",101131.10,7/2/2020,Appliances,Johns and Sons,Lambert Norheny,Collin Mackness,Mobile,59-2117058
997,Finland,"74,480.56",60023.88,3/6/2020,Clothing,Homenick-Marvin,Hube Corey,Wat Bowkley,PC,31-1849120
998,Spain,"87,205.01",69171.01,6/18/2020,Games,Johns and Sons,Emalia Dinse,Manuel Goudie,Tablet,45-3085595
999,Portugal,"107,716.72",86679.64,1/18/2020,Accessories,"Jacobson, Marvin and Brown",Celine Tumasian,Brynn Dempster,Mobile,61-3294149

In [7]:
df.head()  ## used to get first 5 rows

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,4/2/2020,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160

In [8]:
df.tail()   ## used to get last rows

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
995,France,"46,296.26",40319.41,5/15/2020,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
996,Belgium,"118,061.05",101131.10,7/2/2020,Appliances,Johns and Sons,Lambert Norheny,Collin Mackness,Mobile,59-2117058
997,Finland,"74,480.56",60023.88,3/6/2020,Clothing,Homenick-Marvin,Hube Corey,Wat Bowkley,PC,31-1849120
998,Spain,"87,205.01",69171.01,6/18/2020,Games,Johns and Sons,Emalia Dinse,Manuel Goudie,Tablet,45-3085595
999,Portugal,"107,716.72",86679.64,1/18/2020,Accessories,"Jacobson, Marvin and Brown",Celine Tumasian,Brynn Dempster,Mobile,61-3294149

## basic checks

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country            1000 non-null   object
 1    order_value_EUR   1000 non-null   object
 2    cost              1000 non-null   float64
 3   date               1000 non-null   object
 4   category           1000 non-null   object
 5   customer_name      1000 non-null   object
 6   sales_manager      1000 non-null   object
 7   sales_rep          1000 non-null   object
 8   device_type        1000 non-null   object
 9   order_id           1000 non-null   object
dtypes: float64(1), object(9)
memory usage: 78.3+ KB

## Checking missing values count

In [10]:
df.isnull().sum()

country              0
 order_value_EUR     0
 cost                0
date                 0
category             0
customer_name        0
sales_manager        0
sales_rep            0
device_type          0
order_id             0
dtype: int64

## So, in my dataset i have no null values

## Checking duplicates

In [11]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

## Check unique values before standardization

In [12]:
# Check unique values before standardization

print(df['country'].unique())
print(df['category'].unique())
print(df['device_type'].unique())

['Sweden' 'Finland' 'Portugal' 'Spain' 'UK' 'France' 'Netherlands'
 'Belgium' 'Bulgaria' 'Luxembourg' 'Italy' 'Ireland' 'Germany' 'Denmark'
 'Austria']
['Books' 'Games' 'Clothing' 'Beauty' 'Accessories' 'Appliances'
 'Smartphones' 'Outdoors' 'Electronics' 'Other']
['Mobile' 'PC' 'Tablet']

## Data Standardization

In [13]:
# Data Standardization

# Remove extra spaces and standardize text format
df['country'] = df['country'].str.strip().str.title()

df['category'] = df['category'].str.strip().str.title()

df['device_type'] = df['device_type'].str.strip().str.title()

In [14]:
# Check unique values after standardization

print(df['country'].unique()[:10])
print(df['category'].unique()[:10])
print(df['device_type'].unique()[:10])

['Sweden' 'Finland' 'Portugal' 'Spain' 'Uk' 'France' 'Netherlands'
 'Belgium' 'Bulgaria' 'Luxembourg']
['Books' 'Games' 'Clothing' 'Beauty' 'Accessories' 'Appliances'
 'Smartphones' 'Outdoors' 'Electronics' 'Other']
['Mobile' 'Pc' 'Tablet']

## Convert date formats to a consistent type (e.g., dd-mm-yyyy).

In [15]:
# Convert date column to datetime
df['date'] = pd.to_datetime(df['date'])

# Convert to dd-mm-yyyy format
df['date'] = df['date'].dt.strftime('%d-%m-%Y')

## Column Header Standardization

In [16]:
# Check column names before renaming
print("Before Renaming:")
print(df.columns)

# Standardize column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# Check column names after renaming
print("After Renaming:")
print(df.columns)

Before Renaming:
Index(['country', ' order_value_EUR ', ' cost ', 'date', 'category',
       'customer_name', 'sales_manager', 'sales_rep', 'device_type',
       'order_id'],
      dtype='object')
After Renaming:
Index(['country', 'order_value_eur', 'cost', 'date', 'category',
       'customer_name', 'sales_manager', 'sales_rep', 'device_type',
       'order_id'],
      dtype='object')

## Checking data types

In [17]:
# Check data types
print(df.dtypes)

country             object
order_value_eur     object
cost               float64
date                object
category            object
customer_name       object
sales_manager       object
sales_rep           object
device_type         object
order_id            object
dtype: object

In [18]:
df.to_csv("sales_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Short summary of changes

- 1. Loaded the Sales Export 2019–2020 dataset.
- 2. Checked dataset structure and data types.
- 3. Verified missing values and found no null values.
- 4. Checked for duplicate records and removed them if present.
- 5. Standardized text values by removing extra spaces and applying consistent formatting.
- 6. Converted the date column to a consistent format.
- 7. Renamed column headers to lowercase with underscores.
- 8. Validated data types for all columns.
- 9. Saved the cleaned dataset for further analysis.